import type { Community } from "./types";

export const COMMUNITIES: Community[] = [
  {
    slug: "las-olas",
    name: "Las Olas",
    county: "Broward County",
    mileMarker: 8.1,
    heroImage: "/communities/las-olas.webp",
    heroImageAlt: "Las Olas Boulevard in Fort Lauderdale, Florida",
    heroImageCredit: {
      author: "Infrogmation",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Las_Olas_Boulevard,_Fort_Lauderdale,_Florida_02.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
    tagline: "Downtown Fort Lauderdale living near the New River and Las Olas Boulevard.",
    overview:
      "Las Olas is a central Fort Lauderdale district where downtown condos, restaurants, offices, marinas, and the New River sit close together. Buyers comparing the area often weigh walkability, building rules, parking, flood information, boat access, and proximity to the beach.",
    medianPrice: 0,
    highlights: ["Downtown Fort Lauderdale", "New River access", "Condos and townhomes", "Dining and retail"],
    images: [],
  },
  {
    slug: "coral-ridge",
    name: "Coral Ridge",
    county: "Broward County",
    mileMarker: 9.6,
    heroImage: "/communities/coral-ridge.webp",
    heroImageAlt: "The Galleria on Sunrise Boulevard near Coral Ridge in Fort Lauderdale",
    heroImageCredit: {
      author: "Rob Olivera",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:The_Galleria_Mall_-_Fort_Lauderdale,_FL._USA.jpg",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    },
    tagline: "Established Fort Lauderdale neighborhoods between the Intracoastal and US-1 corridor.",
    overview:
      "Coral Ridge includes single-family homes, waterfront streets, condos, and convenient access to central Fort Lauderdale. Property-by-property research matters here because dockage, bridge clearance, flood zones, renovations, and lot characteristics can vary significantly.",
    medianPrice: 0,
    highlights: ["Single-family homes", "Waterfront streets", "Near the Intracoastal", "Central Broward location"],
    images: [],
  },
  {
    slug: "wilton-manors",
    name: "Wilton Manors",
    county: "Broward County",
    mileMarker: 10,
    heroImage: "/communities/wilton-manors.webp",
    heroImageAlt: "Wilton Manors City Hall on Wilton Drive",
    heroImageCredit: {
      author: "Jessica Chesler",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:City_Hall_on_Wilton_Drive.jpeg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
    tagline: "A compact Broward city with residential streets around Wilton Drive.",
    overview:
      "Wilton Manors is a small municipality surrounded by Fort Lauderdale and Oakland Park. Buyers can compare single-family homes, townhomes, condos, canal-front properties, and proximity to Wilton Drive while checking the specific flood, permit, and property records for each address.",
    medianPrice: 0,
    highlights: ["Wilton Drive", "Single-family and condo options", "Canal-front properties", "Central Broward location"],
    images: [],
  },
  {
    slug: "lauderdale-by-the-sea",
    name: "Lauderdale-by-the-Sea",
    county: "Broward County",
    mileMarker: 12.4,
    heroImage: "/communities/lauderdale-by-the-sea.webp",
    heroImageAlt: "Anglin's Fishing Pier at Lauderdale-by-the-Sea, Florida",
    heroImageCredit: {
      author: "John Spade",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Lauderdale_by_the_Sea_Florida_Fishing_Pier_09.jpg",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    },
    tagline: "A beachside town north of Fort Lauderdale with condos and low-rise residential streets.",
    overview:
      "Lauderdale-by-the-Sea sits between the Atlantic Ocean and the Intracoastal corridor. Buyers often compare oceanfront condos, smaller buildings, single-family homes, beach access, building rules, flood information, and insurance considerations.",
    medianPrice: 0,
    highlights: ["Atlantic beach access", "Oceanfront condos", "Low-rise areas", "Near Fort Lauderdale"],
    images: [],
  },
  {
    slug: "hillsboro-beach",
    name: "Hillsboro Beach",
    county: "Broward County",
    mileMarker: 18.9,
    heroImage: "/communities/hillsboro-beach.webp",
    heroImageAlt: "Aerial view of Hillsboro Inlet Lighthouse and Hillsboro Beach",
    heroImageCredit: {
      author: "Yanjipy",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Aerial_Shot_of_Hillsboro_Inlet_Lighthouse.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
    tagline: "A narrow coastal town between the Atlantic and Intracoastal Waterway.",
    overview:
      "Hillsboro Beach is a barrier-island community with oceanfront and Intracoastal properties along Hillsboro Mile. Buyers should evaluate building or property-specific details such as flood information, insurance, seawalls, docks, association documents, reserves, and assessments where applicable.",
    medianPrice: 0,
    highlights: ["Barrier-island location", "Oceanfront property", "Intracoastal property", "Condo and estate options"],
    images: [],
  },
  {
    slug: "boca-raton",
    name: "Boca Raton",
    county: "Palm Beach County",
    mileMarker: 26.2,
    heroImage: "/communities/boca-raton.webp",
    heroImageAlt: "Mizner Park in Boca Raton, Florida",
    heroImageCredit: {
      author: "Elfguy",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Mizner_Park.jpg",
      license: "Public domain",
    },
    tagline: "A large Palm Beach County market spanning beach, downtown, golf, and gated communities.",
    overview:
      "Boca Raton offers a wide range of housing, from downtown and beach-area condos to single-family neighborhoods, waterfront property, golf communities, and gated developments. HOA or club requirements, school assignments, flood information, and property records can differ substantially by address.",
    medianPrice: 0,
    highlights: ["Downtown and beach areas", "Waterfront homes", "Golf communities", "Gated communities"],
    images: [],
  },
  {
    slug: "delray-beach",
    name: "Delray Beach",
    county: "Palm Beach County",
    mileMarker: 31,
    heroImage: "/communities/delray-beach.webp",
    heroImageAlt: "Delray Beach, Florida shoreline off A1A",
    heroImageCredit: {
      author: "Ebyabe",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Delray_Beach_FL_beach_near_A1A_north01.jpg",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    },
    tagline: "Atlantic Avenue, beach access, condos, historic areas, and suburban communities.",
    overview:
      "Delray Beach stretches from the Atlantic coast west through a mix of downtown condos, established neighborhoods, gated communities, and newer development. Buyers can compare walkability near Atlantic Avenue with larger-home options farther west while verifying HOA, flood, permit, and school information by property.",
    medianPrice: 0,
    highlights: ["Atlantic Avenue", "Beach access", "Downtown condos", "Gated communities"],
    images: [],
  },
  {
    slug: "boynton-beach",
    name: "Boynton Beach",
    county: "Palm Beach County",
    mileMarker: 36,
    heroImage: "/communities/boynton-beach.webp",
    heroImageAlt: "Marina Village in Boynton Beach, Florida",
    heroImageCredit: {
      author: "Andyxox",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Marina_Village.jpg",
      license: "Public domain",
    },
    tagline: "Coastal, central, and western neighborhoods across southern Palm Beach County.",
    overview:
      "Boynton Beach includes coastal condos and neighborhoods east of I-95 as well as a large selection of single-family, gated, and age-restricted communities farther west. HOA rules, club structures, school assignments, and insurance considerations vary widely, making address-level research important.",
    medianPrice: 0,
    highlights: ["Coastal and inland options", "Single-family homes", "Gated communities", "55+ communities"],
    images: [],
  },
  {
    slug: "lake-worth-beach",
    name: "Lake Worth Beach",
    county: "Palm Beach County",
    mileMarker: 42,
    heroImage: "/communities/lake-worth-beach.webp",
    heroImageAlt: "Lake Worth Beach pier at sunset",
    heroImageCredit: {
      author: "Gszrir",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Lake_Worth_Florida_Pier.jpg",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    },
    tagline: "An eastern Palm Beach County city with a downtown core and beach access.",
    overview:
      "Lake Worth Beach combines an older downtown grid, cottages and single-family homes, condos, and access to the Intracoastal and Atlantic beach. Renovation history, permits, flood information, historic-district considerations, and lot details are useful items to verify for individual properties.",
    medianPrice: 0,
    highlights: ["Downtown grid", "Beach access", "Older housing stock", "Condos and single-family homes"],
    images: [],
  },
  {
    slug: "west-palm-beach",
    name: "West Palm Beach",
    county: "Palm Beach County",
    mileMarker: 48,
    heroImage: "/communities/west-palm-beach.webp",
    heroImageAlt: "West Palm Beach waterfront and downtown skyline",
    heroImageCredit: {
      author: "Jared",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:West_Palm_Beach_-_Waterfront_-_Intracoastal_Waterway_%26_Downtown_Skyline_-_Panorama_(15300572403).jpg",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    },
    tagline: "Downtown towers, historic neighborhoods, and communities across central Palm Beach County.",
    overview:
      "West Palm Beach offers downtown condos and apartments, established residential neighborhoods, waterfront areas, and suburban communities farther west. Buyers often compare commute access, condo or HOA rules, flood information, taxes, and proximity to downtown amenities.",
    medianPrice: 0,
    highlights: ["Downtown condos", "Historic neighborhoods", "Waterfront areas", "Central county access"],
    images: [],
  },
  {
    slug: "wellington",
    name: "Wellington",
    county: "Palm Beach County",
    mileMarker: 52,
    heroImage: "/communities/wellington.webp",
    heroImageAlt: "Winter Equestrian Festival in Wellington, Florida",
    heroImageCredit: {
      author: "Julia Rubinic",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Beezie_Madden_Onlight_WEF_2008.jpg",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    },
    tagline: "Western Palm Beach County homes, equestrian property, gated communities, and larger lots.",
    overview:
      "Wellington is known for a broad range of single-family neighborhoods and its equestrian community. Buyers may compare gated and non-gated subdivisions, acreage and equestrian properties, HOA rules, school assignments, commute patterns, drainage, and permit history.",
    medianPrice: 0,
    highlights: ["Equestrian property", "Single-family neighborhoods", "Gated communities", "Larger-lot options"],
    images: [],
  },
  {
    slug: "palm-beach-gardens",
    name: "Palm Beach Gardens",
    county: "Palm Beach County",
    mileMarker: 58,
    heroImage: "/communities/palm-beach-gardens.webp",
    heroImageAlt: "9/11 Memorial Plaza in Palm Beach Gardens, Florida",
    heroImageCredit: {
      author: "William ‘Patrick’ Ma…",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Palm_Beach_Gardens,_FL,_USA_-_panoramio_(10).jpg",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    },
    tagline: "Northern Palm Beach County communities with golf, gated neighborhoods, and convenient retail access.",
    overview:
      "Palm Beach Gardens includes country-club and golf communities, gated subdivisions, condos, townhomes, and non-gated neighborhoods. Buyers should compare HOA or club obligations, property taxes, school assignments, insurance, and access to major roads and employment centers.",
    medianPrice: 0,
    highlights: ["Golf communities", "Gated neighborhoods", "Townhomes and condos", "Northern Palm Beach County"],
    images: [],
  },
  {
    slug: "jupiter",
    name: "Jupiter",
    county: "Palm Beach County",
    mileMarker: 66,
    heroImage: "/communities/jupiter.webp",
    heroImageAlt: "Jupiter Inlet Lighthouse viewed from across the inlet",
    heroImageCredit: {
      author: "Dk100",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Jupiter_Lighthouse.JPG",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    },
    tagline: "Northern Palm Beach County living near the Loxahatchee River, Intracoastal, and Atlantic coast.",
    overview:
      "Jupiter includes waterfront homes, beach-area condos, golf and gated communities, and suburban neighborhoods extending inland. Boaters and waterfront buyers should verify bridge clearance, dock and seawall condition, flood information, permits, and insurance details for the specific property.",
    medianPrice: 0,
    highlights: ["Waterfront homes", "Beach-area condos", "Golf communities", "Boating access"],
    images: [],
  },
];

export async function getAllCommunities(): Promise<Community[]> {
  return [...COMMUNITIES].sort((a, b) => a.mileMarker - b.mileMarker);
}

export async function getCommunityBySlug(slug: string): Promise<Community | undefined> {
  return COMMUNITIES.find((c) => c.slug === slug);
}
